language: r

branches:
  only:
    - master

script:
  - Rscript -e "rmarkdown::render('GSG_Induction_Managing_your_career.Rmd', output_file = "index.html", output_dir = 'docs')"

cache:
  packages: yes
  directories:
    - $HOME/bin

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
  local_dir: docs
